#!/bin/sh
#
# Make a total backup of the system and
# transfer the backup via ssh to some
# remote destination.

# You may want to change the location of the backup file
# to make it more secure and perhaps the file name itself.

if [ ! -f /etc/config.data/backup.conf ]; then
    echo "You need to configure '/etc/config.data/backup.conf'"
    echo "Example contents:"
    echo " BACKUP_USER=root"
    echo " BACKUP_HOST=host.domain.se"
    echo " BACKUP_FILENAME=/tmp/bifrost"
    echo " BACKUP_ADD_DATE=yes"
    exit 1
fi
. /etc/config.data/backup.conf

[ "$BACKUP_FILENAME" ] || BACKUP_FILENAME="/tmp/bifrost"

DATE=""
[ "$BACKUP_ADD_DATE" = yes ] && DATE="-$(date +%Y-%m-%d)"

FILENAME="${BACKUP_FILENAME}$DATE.tar.gz"

echo
echo "Backing up everything through an ssh tunnel."
echo "After entering the password, please wait for"
echo "the shell prompt to come back."
echo "The destination file is '$FILENAME'."
echo

read FLAG < /etc/config.flags/rwsystem
[ "$FLAG" != yes ] && remount r

cd /
umount -n /mnt 2> /dev/null

(mount -nr LABEL=bifrost /mnt||mount -n LABEL=bifrost /mnt||mount -t ext4 -nr LABEL=bifrost /mnt||mount -t ext4 -n LABEL=bifrost /mnt ) 2> /dev/null

[ $? = 0 ] || exit 1

cd /mnt || exit 1

tar czpf - . | ssh $BACKUP_USER@$BACKUP_HOST "umask 077;cat - > $FILENAME"

cd /
umount -n /mnt 2> /dev/null
