#!/bin/bash

if [ ! -f /etc/opt/sources.list ]; then
   echo "'/etc/opt/sources.list' is missing!"
   exit 1
fi

function fetchlist {
	 local REALURL=$1
	 while read REPO; do
		NAME=$REPO
	 	[ "$REALURL" ] || NAME=$(echo $REPO|cut -d / -f 1-3)
	       wget -q --no-check-certificate "$REPO" -O-|sed 's/href="/\nhref="/'|grep ^href|cut -d \" -f 2|grep '^opt.*tar.gz'|xargs -n 1 echo "$NAME"|tr ' ' '/'
	 done
}

if [ -z "$1" ]; then
    echo "opt-get list|fetch|install|update [name]"
    exit 0
fi

# opt-get list
if [ "$1" = list ]; then
   vers -p -l $(cat /etc/opt/sources.list|fetchlist)
   exit 0
fi

function opt_update {
	while read L; do
		P=$(vers -n $L)
		PV=$(vers $L)
		PV=${PV%.tar.gz*}
		for F in /opt/*/pkgversion; do
			if grep -q "^$P" $F; then
				read V < $F
				if [ $V != $PV ]; then
					echo $PV
				fi
			fi
		done
	done
}

# opt-get update
if [ "$1" = update ]; then
   for PKG in $(vers -p -l $(cat /etc/opt/sources.list|fetchlist)|opt_update); do
	$0 install $PKG
   done
   exit 0
fi

# opt-get install <pkg>
if [ "$1" = install ]; then
   pkg=$(vers -p -l $(cat /etc/opt/sources.list|fetchlist y)|grep "/$2"|head -n 1)
   [ "$pkg" ] || exit 1
   echo "Install $pkg ? y/n"
   read ANS
   [ "$ANS" != y ] && exit 1
   remount w
   rc=$?
   cd /
   if wget --no-check-certificate "$pkg" -O /tmp/p$$.tar.gz; then
       tar xf /tmp/p$$.tar.gz
       rm -f /tmp/p$$.tar.gz
   fi
   [ "$rc" = 0 ] && remount r
   exit 0
fi

# opt-get fetch <pkg>
if [ "$1" = fetch ]; then
   pkg=$(vers -p -l $(cat /etc/opt/sources.list|fetchlist y)|grep "/$2"|head -n 1)
   [ "$pkg" ] || exit 1
   echo "Fetch $pkg ? y/n"
   read ANS
   [ "$ANS" != y ] && exit 1
   cd /tmp
   wget --no-check-certificate "$pkg"
   exit 0
fi

