#!/bin/sh
#
# We will check that some daemons are running
# and if not - restart them.
#

# Check for sshd
if [ "$(ps acxh|grep -c sshd)" = 0 ]; then
        /usr/sbin/sshd
fi

# Check for syslogd or syslog-ng
if [ "$(ps acxh|grep -c syslog)" = 0 ]; then
        /etc/rc.d/rc.syslog
fi

# Log internal temperature
#if [ "$(grep -c LM78 /proc/ioports)" = 1 ] ; then
#    export TEMP=`cat /proc/sys/dev/lm78/status/temperature`
#    logger "temperature is $TEMP degrees Celcius"
#fi
